---
title: "useful_commands"
author: "Jaime Abraham Castro-Mondragon"
date: 'Last update: `r Sys.Date()`'
output: 
  html_document:
    theme: cosmo
    toc: yes
    toc_float:
      collapsed: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

```

## Introduction

In this document you will find many commands from multiple languages, for instance `R`, `python`, `bash`, `Snakemake`, or other. I use this commands frequently and I think they are very useful **but easy to forget**.

So, to avoid searching on the `bash history`, it is better to have a repository with all of them, enjoy.



# `aws`

### `log in`

Run the command and open the browser to confirm

```{bash aws_sso_login, echo=TRUE, eval=FALSE}
aws sso login
```



# `git`

### Create a new branch from a previous `commit`

Use `git log` to get the commit hash, `git branch` to create a new branch, and `git switch` to modify the new branch.

Don't forget to double check the branch you are working with using `git status` 

```{bash git_branch_from_commit, echo=TRUE, eval=FALSE}
git log
git branch new_branch_name commit_hash
git switch new_branch_name
```


### Merge a `branch` into `main`

Don't forget to double check the branch you are working with using `git status`  and list the branches with `git branch`

```{bash merge_branch_to_main, echo=TRUE, eval=FALSE}

# Go to the branch
git checkout branch_to_merge

# FETCH_HEAD
git pull origin main

# go to main branch and merge
git checkout main
git merge branch_to_merge

# If needed add the files with differences
git add [resolved_files]

# No -m 
git commit

# Push merged branch to main
git push origin main
```



### `git tag`

First `git commit` your changes before adding a new `tag` .

```{bash git_tag, echo=TRUE, eval=FALSE}
git commit -m 'Your message' folder/your_updated_file.txt
git push
git tag v1.2.4
git push --tags
```



# `python`

### module version

We can use `pip` from the command line .

```{bash pip_show, echo=TRUE, eval=FALSE}
pip show module_name
```


### `poetry` basics

Add, update or remove modules .

```{bash poetry_basics, echo=TRUE, eval=FALSE}

poetry update module

# Add a module or a specific version or the latest version
poetry add python
poetry add python=3.8
poetry add python@latest

# Remove a module
poetry remove python
```


